[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]
via_ir = true

remappings = [
    "@aave/core-v3/=lib/aave-v3-core/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink/",
    "forge-std/=lib/forge-std/src/",
]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/469a0721f318401584ab3639fb548d63"

[etherscan]
mainnet = { key = "D83MMXC2TKAV813NZTS4SR55VF4BN3BV2G}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
